Feature add mailer
Crysicia/THPNext-ECommerce pull request #66
Opened 2019-01-31 18:07 UTC by CitizenYY

2019-01-31 18:15 UTC, Crysicia requested changes

2019-01-31 18:15 UTC, Crysicia commented on config/environments/development.rb
> +    }
Prefer the new hash syntax

2019-01-31 18:15 UTC, Crysicia commented on config/environments/test.rb
> +    }
Prefer the new hash syntax

2019-01-31 18:15 UTC, Crysicia commented on app/models/user.rb
> +  end
??? Where is this mailer ?

2019-01-31 18:26 UTC, stephan-dev commented on app/models/user.rb
> +  end
I concur

2019-01-31 18:40 UTC, CitizenYY commented on config/environments/development.rb
> +    }
ok done

2019-01-31 18:41 UTC, CitizenYY commented on app/models/user.rb
> +  end
oops, added

2019-01-31 22:54 UTC, stephan-dev approved these changes
approved with the changes

2019-02-01 00:13 UTC, Crysicia submitted a review, later dismissed

2019-02-01 09:53 UTC, Crysicia commented
@CitizenYY I think you forgot to add SendGrid ;)

2019-02-01 11:47 UTC, merged